Modify denominators to be specific for each clinical condition
opensafely/pharmacy-first pull request #30
Opened 2024-10-09 11:16 UTC by viv3ckj

Closes #23 
Denominators added (excluding exclusions). 
Will do commenting and tidying, with exclusions in next commit.

2024-10-09 12:45 UTC, milanwiedemann approved these changes
this looks really great already 🚀 left some ideas for you to consider

2024-10-09 12:45 UTC, milanwiedemann commented on analysis/measures_definition_pf_codes_conditions.py
> +denominators = {
great implementation, I'd just make it a bit clearer that these are the denominators for the pharmacy first conditions

```suggestion
pf_condition_denominators = {
```

2024-10-09 12:45 UTC, milanwiedemann commented on analysis/measures_definition_pf_codes_conditions.py
> +            denominator=denominators[condition_name],
this looks like a great way to do it! but I think we also need to add this to the denominaotr of the overall measure?

```py
    measures.define_measure(
        name=f"count_{condition_name}",
        numerator=numerator,
        denominator=pf_condition_denominators[condition_name],
        intervals=months(monthly_intervals).starting_on(start_date),
    )
```

also updating the suggested name change here:

```suggestion
            denominator=pf_condition_denominators[condition_name],
```

2024-10-09 12:45 UTC, milanwiedemann commented on analysis/measures_definition_pf_codes_conditions.py
> +denominator_uncomplicated_uti = (age>=16) & (age<=64) & (patients.sex.is_in(["female"]))
we should add a comment above this line explaining which part of the denominaotr rules we already implemented, and importantly also that we didnt to the exclusions yet.

2024-10-09 19:43 UTC, viv3ckj commented
Thanks Milan, I've made changes based on your comments.

2024-10-14 09:51 UTC, milanwiedemann requested changes
I think we should implement the denominators (and tests like you mentioned in #32) first in a dataset definition before adding them here. I'll make PR with suggestions

2024-10-14 12:38 UTC, milanwiedemann approved these changes

2024-10-14 12:40 UTC, merged